**1- Importing the Required Libraries**

We import the libraries needed for data analysis, machine learning, visualization, and statistical plotting: Pandas, NumPy, Scikit-learn, Matplotlib, and Seaborn.

In [2]:
import sys
import os

import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns 
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [3]:

sys.path.append(os.path.abspath('..'))

from config.path import DATA_RAW_PATH

In [4]:
voiture_df = pd.read_csv(DATA_RAW_PATH)

In [5]:
voiture_df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007.00,60000,70000.00,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007.00,135000,50000.00,Petrol,Individual,Manual,NaN
2,Hyundai Verna 1.6 SX,2012.00,600000,100000.00,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017.00,250000,46000.00,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014.00,450000,141000.00,Diesel,Individual,Manual,Second Owner

In [6]:
voiture_df['seller_type'].value_counts()

seller_type
Individual          3198
Dealer               976
Trustmark Dealer     101
Name: count, dtype: int64

In [7]:
voiture_df.shape

(4340, 8)

In [8]:
voiture_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   str
 1   year           4297 non-null   float64
 2   selling_price  4340 non-null   int64
 3   km_driven      4167 non-null   float64
 4   fuel           4254 non-null   str
 5   seller_type    4275 non-null   str
 6   transmission   4340 non-null   str
 7   owner          4254 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 271.4 KB

In [9]:
voiture_df.describe()

         year  selling_price  km_driven
count 4297.00        4340.00    4167.00
mean  2013.09      504127.31   66237.20
std      4.22      578548.74   46635.46
min   1992.00       20000.00       1.00
25%   2011.00      208749.75   35000.00
50%   2014.00      350000.00   60000.00
75%   2016.00      600000.00   90000.00
max   2020.00     8900000.00  806599.00

In [10]:
voiture_df.describe(include=['O'])

/tmp/ipykernel_46756/15697581.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  voiture_df.describe(include=['O'])

                          name    fuel seller_type transmission        owner
count                     4340    4254        4275         4340         4254
unique                    1491       5           3            2            5
top     Maruti Swift Dzire VDI  Diesel  Individual       Manual  First Owner
freq                        69    2116        3198         3892         2771

In [11]:
print(voiture_df.isnull().sum())

print('=' * 50)

print(voiture_df.isnull().sum() / len(voiture_df) * 100)

print('=' * 50)

print(voiture_df.duplicated().sum())

name               0
year              43
selling_price      0
km_driven        173
fuel              86
seller_type       65
transmission       0
owner             86
dtype: int64
==================================================
name            0.00
year            0.99
selling_price   0.00
km_driven       3.99
fuel            1.98
seller_type     1.50
transmission    0.00
owner           1.98
dtype: float64
==================================================
635

**2- Indicuduel column**

In [12]:

print(voiture_df['owner'].value_counts(normalize=True))

print( '=' * 50 )

print(voiture_df['fuel'].value_counts(normalize=True))


print( '=' * 50 )

print(voiture_df['seller_type'].value_counts(normalize=True))

owner
First Owner            0.65
Second Owner           0.25
Third Owner            0.07
Fourth & Above Owner   0.02
Test Drive Car         0.00
Name: proportion, dtype: float64
==================================================
fuel
Diesel     0.50
Petrol     0.49
CNG        0.01
LPG        0.01
Electric   0.00
Name: proportion, dtype: float64
==================================================
seller_type
Individual         0.75
Dealer             0.23
Trustmark Dealer   0.02
Name: proportion, dtype: float64